### PR TITLE
[#3] Add gibhtub action build with nix

### LINKED ISSUE #3: Setup GiHub Action

### PR DESCRIPTION
**Pull request by mstruebing**
closes #3

### CODE REVIEW

**Comment by mstruebing** [comment]
I hope that would work, but only maintainers can activate github actions.

**Review by chshersh — COMMENTED** [review]
@mstruebing Thanks for your work! In our projects we're using the following template for GitHub CI actions with `nix` and `cachix`:

* https://github.com/vrom911/haskeller-answers/blob/master/.github/workflows/ci.yml

However, at this point, it doesn't work smoothly and takes 2 hours to complete. `cachix-action` doesn't support caching of repositories like this one. See the following issue for more details:

* https://github.com/cachix/cachix-action/issues/9

That's why we haven't added GitHub CI actions to this project yet, because waiting 2 hours each time before merging a minor code change seems like a waste of time and resources at this point. However, once `cachix-action` fixes its behaviour, we're happy to add it here!

Also, I want to mention that GitHub CI actions don't require any enabling. We only need to add a secret key to kowainik cache in the settings for this repo. But since the free cache is limited to 10 GBs and since we're not planning to add CI to this project until bugfixes in `cachix`, I would prefer not to waste our limited cache storage on currently inefficient builds.

**Comment by mstruebing** [comment]
Sure, I agree that it doesn't make sense at all then.
If the bug is fixed anytime I would be happy to work further on it.

**Comment by vrom911** [comment]
This is outdated.

**Pull request closed without merging**
